# Generated by Django 3.1 on 2020-11-03 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0003_auto_20201102_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pem_kreditm',
            name='jatuh_tempo',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='pem_tunaim',
            name='jatuh_tempo',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='pend_lainm',
            name='jatuh_tempo',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='penjualan1m',
            name='jatuh_tempo',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
