# Generated by Django 3.1 on 2020-11-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_auto_20201029_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pem_kreditm',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olshop.barangm'),
        ),
    ]
